Added ASCII art and soundtrack suggestion
edutr98/MNXB01-learn pull request #1
Opened 2022-10-10 15:50 UTC by floridop

Added some content to your story. You are free to ask me to do any change you like before approving!

Great beginning of a story by the way!

2022-10-26 14:12 UTC, floridop commented
Hi @edutr98 

To complete this homework you need to merge this contribution. You can ask me to do something before. Please check canvas.

2022-10-26 14:18 UTC, edutr98 requested changes

2022-10-26 14:18 UTC, edutr98 commented on README.md
> +Soundtrack: <https://youtu.be/wZdZKolMIl0>
Great song! but what do you think about these two options:
<https://www.youtube.com/watch?v=C2-YwsEq0-0&list=PL-QKUHF6WxKukMmupCCjkVfJS76XK9Ezv&index=1>
<https://www.youtube.com/watch?v=g9clrY3kkXY>

2022-11-01 15:22 UTC, merged

2022-11-01 17:48 UTC, floridop commented
I'll close this part of the homework, but if there is something else 
you're curious to try and I am available I'll be happy to test.